just kill geckdriver

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -65,12 +65,6 @@ jobs:
         with:
           python-version: 3.12
 
-      - name: Check preinstalled python+geckodriver
-        shell: bash
-        run: |
-          which firefox && sudo dpkg -S $(which firefox)
-          which geckodriver && sudo dpkg -S $(which geckodriver)
-
       - name: Install apt stuff and other dependencies
         shell: bash
         run: |
@@ -84,7 +78,10 @@ jobs:
             ruby-pygments.rb \
             firefox-esr \
             tree
+          # fix failed to install firefox bin/symlink
           which firefox || sudo ln -s /usr/bin/firefox-esr /usr/bin/firefox
+          # remove old geckodriver
+          which geckodriver && sudo rm $(which geckodriver) || exit 0
           pip install uv
 
       - name: Install Python requirements.txt globally
@@ -103,7 +100,7 @@ jobs:
           apt show firefox-esr
           dpkg -L firefox-esr
           firefox --version
-          which geckodriver && geckodriver --version
+          which geckodriver && geckodriver --version || exit 0
 
       - name: Run chapter test
         shell: bash
